#standard params in most cases (ocaml usually generates them with the configure script)
RANLIBCMD=ranlib
BYTECC=gcc
BYTECCCOMPOPTS=-fno-defer-pop -Wall -Wno-unused -U_WIN32 -D_FILE_OFFSET_BITS=64
BYTECCLINKOPTS=
BYTECCLIBS= -lm  -ltermcap 
BYTECCRPATH=
EXE=.exe
SHAREDCCCOMPOPTS=
ARCH=i386
MODEL=default
SYSTEM=cygwin
NATIVECC=gcc
NATIVECCCOMPOPTS=-Wall -Wno-unused -U_WIN32 -D_FILE_OFFSET_BITS=64
NATIVECCPROFOPTS=-Wall -Wno-unused -U_WIN32 -D_FILE_OFFSET_BITS=64
NATIVECCLINKOPTS=
NATIVECCRPATH=
NATIVECCLIBS= -lm 
BINUTILS_OBJCOPY=/usr/bin/objcopy
BINUTILS_NM=/usr/bin/nm