(************************************************************************)
(*                                                                      *)
(*                                CamIL                                 *)
(*                                                                      *)
(* created by  Bruno Pagano, projet Cristal, INRIA Rocquencourt (2000)  *)
(* modified by Emmanuel Chailloux & Raphael Montelatici, PPS (2003-2006)*)
(*                                                                      *)
(************************************************************************)

val system_ns : string
val text_ns : string
val camil_ns : string
val object_ref : Il.typeref
val object_type : Il.elementType
val object_ctor : Il.methodref
val objtab_type : Il.elementType
val int8_type : Il.elementType
val int16_type : Il.elementType
val int32_ref : Il.typeref
val int32_boxed_type : Il.elementType
val int32_type : Il.elementType
val int32_ctor : Il.methodref
val int64_ref : Il.typeref
val int64_boxed_type : Il.elementType
val int64_type : Il.elementType
val int64_ctor : Il.methodref
val nint_ref : Il.typeref
val nint_boxed_type : Il.elementType
val nint_type : Il.elementType
val nint_ctor : Il.methodref
val nint_ofint : Il.methodref
val float64_ref : Il.typeref
val float64_boxed_type : Il.elementType
val float64_type : Il.elementType
val float64_ctor : Il.methodref
val string_ref : Il.typeref
val string_type : Il.elementType
val char_ref : Il.typeref
val char_type : Il.elementType
val char_arr_type : Il.elementType
val bool_ref : Il.typeref
val bool_type : Il.elementType
val builder_ref : Il.typeref
val builder_type : Il.elementType
val builder_ctor : Il.methodref
val builder_conv : Il.methodref
val builder_length : Il.methodref
val builder_getchars : Il.methodref
val builder_setchars : Il.methodref
val string_ctor : Il.methodref
val string_length : Il.methodref
val string_getchars : Il.methodref
val string_to_chararray : Il.methodref
val string_compare : Il.methodref
val convert_ref : Il.typeref
val convert_type : Il.elementType
val charofint : Il.methodref
val intofchar : Il.methodref
val math_ref : Il.typeref
val math_abs : Il.methodref
val boxint_ref_pvt : Il.typeref
val boxint_is : Il.methodref
val boxint_tag : Il.methodref
val sysexn_ref : Il.typeref
val sysexn_type : Il.elementType
val sysexn_ctor : Il.methodref
val exn_ref : Il.typeref
val exn_type : Il.elementType
val exn_field : Il.fieldref
val exn_ctor : Il.methodref
val exn_raise : Il.methodref
val exn_embed : Il.methodref
val closure_ref : Il.typeref
val closure_type : Il.elementType
val closure_ctor : Il.methodref
val closure_apply : Il.methodref
val clospapp_ref : Il.typeref
val clospapp_type : Il.elementType
val clospapp_ctor : Il.methodref
val clospapp_genapply : Il.methodref
val clospapp_cur : Il.fieldref
val clospapp_envt : Il.fieldref
val clospapp_copy : Il.methodref
val camil_hash_ref : Il.typeref
val camil_hash_code : Il.methodref
val record_ref : Il.typeref
val record_type : Il.elementType
val record_ctor : Il.methodref
val record_equals : Il.methodref
val record_compare : Il.methodref
val record_hashcode : Il.methodref
val variant_ref : Il.typeref
val variant_type : Il.elementType
val variant_ctor : Il.methodref
val variant_tag : Il.fieldref
val variant_size : Il.fieldref
val variant_equals : Il.methodref
val variant_compare : Il.methodref
val variant_hashcode : Il.methodref
val variant_optim_cc_ref : Il.typeref
val camil_list_nil_ref : Il.typeref
val camil_list_cons_ref : Il.typeref
val camil_option_none_ref : Il.typeref
val camil_option_some_ref : Il.typeref
val cst_ref : Il.typeref
val cst_type : Il.elementType
val cst_failure : Il.fieldref
val cst_assertfailure : Il.fieldref
val cst_matchfail : Il.fieldref
val cst_invargt : Il.fieldref
val cst_notfound : Il.fieldref
val cst_endoffile : Il.fieldref
val cst_outofmemory : Il.fieldref
val cst_stackoverflow : Il.fieldref
val cst_syserror : Il.fieldref
val cst_managedexception : Il.fieldref
val comp_ref : Il.typeref
val comp_type : Il.elementType
val comp_equals : Il.methodref
val comp_compare : Il.methodref
val comp_lessthan : Il.methodref
val comp_greaterthan : Il.methodref
val comp_lessequal : Il.methodref
val comp_greaterequal : Il.methodref
val camilstring_ref : Il.typeref
val camilstring_setsafe : Il.methodref
val camilstring_getsafe : Il.methodref
val string_of_object : Il.methodref
val bldstr_of_object : Il.methodref
val chararray_of_object : Il.methodref
val string_setchars : Il.methodref
val array_ref : Il.typeref
val array_setsafe : Il.methodref
val array_getsafe : Il.methodref
val camil_obj_ref : Il.typeref
val camil_obj_block : Il.methodref
